In [2]:
import os
import pydicom
from PIL import Image
import pandas as pd

In [8]:
df=pd.read_csv('../222.csv')
df.head()

,住院号,姓名,性别,年龄,入院时体温,心率,收缩压,舒张压,体重,身高,...,3V/4pai.1,2/3次方2,等v2的s,SR2,真正的SF2,vequS1（等体积的球的表面积）,vequS2,sd1,sd2,SF差值
0,821657.0,刘继军,1.0,61.0,36.5,84.0,180.0,117.0,NaN,NaN,...,2353.285794,176.922519,2223.273841,0.662427,0.759904,2219.090338,2223.273877,702.559662,7634.146123,0.000371
1,822545.0,胡生朗,1.0,75.0,36.8,60.0,134.0,82.0,NaN,NaN,...,8198.047646,406.574646,5109.167428,0.489897,0.621446,5031.214997,5109.167510,2552.505003,29230.732490,-0.041977
2,822853.0,康小玉,2.0,56.0,36.9,87.0,145.0,87.0,68.0,NaN,...,1642.259459,139.196350,1749.192839,0.692638,0.782836,1636.142203,1749.192867,367.987797,5129.887133,-0.033549
3,825791.0,强光荣,1.0,71.0,36.6,90.0,168.0,101.0,78.0,NaN,...,2638.375283,190.937418,2399.390247,0.222695,0.367401,2274.847854,2399.390285,1639.082146,8652.209715,-0.213818
4,827598.0,李建芳,2.0,66.0,36.8,84.0,121.0,81.0,NaN,NaN,...,3001.415683,208.073816,2614.732557,0.650622,0.750849,2505.619115,2614.732599,762.220885,9957.567401,-0.015902

In [9]:
selected_columns = df[['住院号', '脑出血位置1']]

In [11]:
selected_columns.head()

        住院号        脑出血位置1
0  821657.0  Subtentorial
1  822545.0  Subtentorial
2  822853.0          Deep
3  825791.0          Deep
4  827598.0          Deep